apiVersion: v1
appVersion: "1.23.1"
description: A Helm chart to install vaultwarden
name: bitwarden
version: 1.23.1
home: https://github.com/satish-labs/bitwarden-server
maintainers:
- name: Satish
  email: satish@satishweb.com
