# Override all names
nameOverride: ""
fullnameOverride: ""

# Bitwarden configuration.
# The below values are used to construct a config map, which will be provided
# to the bitwarden_rs container on start up.
# For details about the options, see: https://github.com/dani-garcia/bitwarden_rs/wiki
bitwarden:
  # # Allow registration of new users
  # # See: https://github.com/dani-garcia/bitwarden_rs/wiki/Disable-registration-of-new-users
  signups_allowed: false

  # # Allow current users to invite new users even if registrations are otherwise disabled.
  # # See: https://github.com/dani-garcia/bitwarden_rs/wiki/Disable-invitations
  # invitations_allowed: true

  # # Email of the unique server administrator account
  # # See: https://github.com/dani-garcia/bitwarden_rs#configure-server-administrator
  # server_admin_email: admin@example.com

  # # Websocket support for notifications
  # # See: https://github.com/dani-garcia/bitwarden_rs/wiki/Enabling-WebSocket-notifications
  websocket_enabled: false
  websocket_port: 3012

  # # Needed for U2F authentification
  # # See: https://github.com/dani-garcia/bitwarden_rs/wiki/Enabling-WebSocket-notifications
  # domain: https://bw.domain.tld

  # # API request size limits
  # # See: https://github.com/dani-garcia/bitwarden_rs/wiki/Changing-the-API-request-size-limit
  # rocket_limits: "{json=10485760}"

  # # Number of workers to spin up for the service
  # # See: https://github.com/dani-garcia/bitwarden_rs/wiki/Changing-the-number-of-workers
  # rocket_workers: 10

  # # SMTP settings, for sending out emails
  # # See: https://github.com/dani-garcia/bitwarden_rs/wiki/SMTP-configuration
  # smtp_host: smtp.domain.tld
  # smtp_from: bitwarden@domain.tld
  # smtp_port: 587
  # smtp_ssl: true
  # smtp_username: username
  # smtp_password: password

  # Show password hint instead of sending it via email
  # See: https://github.com/dani-garcia/bitwarden_rs/wiki/Password-hint-display
  show_password_hints: false

  # Enable Vault interface, when disabled, only API is served
  # See: https://github.com/dani-garcia/bitwarden_rs/wiki/Disabling-or-overriding-the-Vault-interface-hosting
  # TODO: enable settings web-vault content; init-container + shared storage + web-vault path?
  web_vault_enabled: true

  # # Logging to a specific file
  # # See: https://github.com/dani-garcia/bitwarden_rs#logging
  # log_file: "/data/bitwarden.log"

  # # Log level: trace, debug, info, warn, error or off
  # log_level: info
  # extended_logging: true

  # Port to serve http requests on. Define it accordingly to the service's target_port
  rocket_port: 8080

  # NOTE: HTTPS cannot be set here, as it is derived from the ingress configuration below.
  # NOTE: DATA_FOLDER cannot be set here, as it is derived from the storage.path below.
  # TODO: Support DATABASE_URL, ATTACHMENTS_FOLDER, ICON_CACHE_FOLDER
  # TODO: Support fail2ban?


# Optional name of the Kubernetes secret object. If provided this will be loaded
# as environment variables into the Bitwarden deployment.
#
# Use this secret for these values:
# ADMIN_TOKEN
# YUBICO_CLIENT_ID
# YUBICO_SECRET_KEY
secrets:
  name: null

deployment:
  # Image used for the deployment
  # See: https://github.com/dani-garcia/vaultwarden
  image:
    repository: vaultwarden/server
    tag: 1.29.2
    pullPolicy: IfNotPresent
    pullSecrets: []
  command: [ "/start.sh" ]
  # command: [ "sh", "-c", "sleep 9999999" ]
  # Resources, etc, for the deployment pod
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  # Disable for debugging mode
  healthCheck:
    enabled: true

securityContext:
  enabled: false
  runAsNonRoot: true
  fsGroup: 99
  runAsGroup: 99
  runAsUser: 99

# Should not be changed
service:
  type: ClusterIP
  port: 8080
  target_port: 8080
  # externalIPs:
  # - x.x.x.x
  # - x.x.x.x
  # externalTrafficPolicy: Local

# Settings regarding persistent storage
# TODO: Support DATABASE_URL + ATTACHMENTS_FOLDER + ICON_CACHE_FOLDER
# See: https://github.com/dani-garcia/bitwarden_rs#changing-persistent-data-location
storage:
  # Whether storing persistent data is enabled or not
  enabled: true
  storageClassName: null
  # Where to store persistent data
  path: "/bw-data"
  # The maximum size of the persisted data
  size: 100Mi

# Settings regarding backup
backup:
  # Whether backup is enabled or not
  enabled: true

  persistence:
    enabled: true
    storageClassName: null
    # Where to store the backup data
    path: "/bw-backup"
    # The maximum size of the persisted backup data
    size: 5Gi

  # Cron schedule for the backup job (currently at 3:00 every night)
  schedule: "* 3 * * *"

  config:
    source_database: "/bw-data/db.sqlite3"
    backup_database: "/bw-data/backup.sqlite3"
    timestamp_backup: false
    timestamp_file: "/bw-backup/timestamp"

  secrets:
    name: null

  # Image used for backup run
  # See: https://github.com/Skeen/bitwarden_rs_backup
  image:
    repository: skeen/bitwarden_rs_backup
    tag: latest
    pullPolicy: IfNotPresent
    pullSecrets: []

  # Resources, etc, for the backup pod(s)
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}

# Ingress configuration
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  host: bitwarden.domain.tld
  tls:
    secretName: bitwarden-tls-secret

# Additional resources
resources:
  enabled: true
  specs: |-
    apiVersion: v1
    kind: Namespace
    metadata:
      name: bitwarden
